apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: helm-kustomize-plugin
spec:
  version: v1.0
  init:
    command: [sh, /var/run/argocd/helm-kustomize-plugin/init.sh]
  generate:
    command: [sh, /var/run/argocd/helm-kustomize-plugin/generate.sh]
  discover:
    find:
      command: [sh, -c, find . -name kustomization.yaml]
